In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [3]:
import numpy as np

vector_10_to_49 = np.arange(10, 50)

print(vector_10_to_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
import numpy as np

matrix_3x3 = np.arange(9).reshape(3, 3)

print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)

print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
import numpy as np

# Create a 10x10 array with random values
random_array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 array:")
print(random_array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Random 10x10 array:
[[0.13389918 0.98492403 0.60032656 0.59438968 0.57660455 0.92929685
  0.76395408 0.94218787 0.8403246  0.14146128]
 [0.92755849 0.29151112 0.58227616 0.39404477 0.06198417 0.77287074
  0.17077737 0.4430006  0.16008166 0.07344294]
 [0.85973172 0.72130727 0.43867218 0.18033214 0.53748709 0.44991746
  0.4856483  0.80241929 0.59967381 0.54225575]
 [0.29148366 0.51106563 0.05388389 0.84133423 0.39544408 0.87939203
  0.3873653  0.11772889 0.00489099 0.02091264]
 [0.39687994 0.15620352 0.60829549 0.76691521 0.45505074 0.72558106
  0.98865404 0.19461533 0.63873849 0.76145516]
 [0.03993117 0.83091853 0.44345943 0.6494414  0.93192499 0.78873714
  0.58144876 0.93827745 0.91278164 0.89888914]
 [0.06594087 0.98511437 0.54905704 0.57482303 0.11110652 0.50701105
  0.60925315 0.4293773  0.63581685 0.75334477]
 [0.34719806 0.25289711 0.90627761 0.41804479 0.23186333 0.37403273
  0.57075883 0.76618191 0.78314227 0.16878236]
 [0.29247743 0.38665393 0.41629866 0.57493529 0.30823948 0.0

6. Create a random vector of size 30 and find the mean value.

In [10]:
import numpy as np

# Create a random vector of size 30
random_vector = np.random.rand(30)

# Find the mean value
mean_value = random_vector.mean()

print("Random Vector:")
print(random_vector)
print("\nMean Value:", mean_value)


Random Vector:
[0.94705619 0.97979288 0.01910833 0.63877577 0.07484906 0.68510216
 0.76764387 0.81991419 0.86029284 0.57523564 0.93885963 0.61345148
 0.77706403 0.36372519 0.15751134 0.47515982 0.00725034 0.58896283
 0.0830494  0.43419815 0.27221225 0.35163638 0.89842391 0.42512384
 0.67086257 0.13051154 0.68269372 0.71800992 0.05689382 0.0035587 ]

Mean Value: 0.5005643258389022
